[package]
name = "vista-sdk"
version = "0.3.3"
edition = "2021"
description = "Rust bindings for the DNV Vista SDK - VIS and ISO 19848"
license = "MIT"
repository = "https://github.com/dnv-opensource/vista-sdk"
links = "dnv-vista-sdk-c"

[dev-dependencies]
serde_json = "1"

[[example]]
name = "core_codebooks"
path = "examples/core/codebooks.rs"
[[example]]
name = "core_gmod_path"
path = "examples/core/gmod_path.rs"
[[example]]
name = "core_gmod"
path = "examples/core/gmod.rs"
[[example]]
name = "core_imo_number"
path = "examples/core/imo_number.rs"
[[example]]
name = "core_local_id"
path = "examples/core/local_id.rs"
[[example]]
name = "core_locations"
path = "examples/core/locations.rs"
[[example]]
name = "core_universal_id"
path = "examples/core/universal_id.rs"
[[example]]
name = "core_vis_versioning"
path = "examples/core/vis_versioning.rs"
[[example]]
name = "query_metadata_tags_query"
path = "examples/query/metadata_tags_query.rs"
