// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Vista.SDK.Transport.Avro.TimeSeriesData
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	
	
	public partial class EventDataSet : ISpecificRecord
	{
		public static Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""EventDataSet"",""namespace"":""Vista.SDK.Transport.Avro.TimeSeriesData"",""fields"":[{""name"":""TimeStamp"",""type"":{""type"":""long"",""logicalType"":""timestamp-micros""}},{""name"":""DataChannelID"",""type"":""string""},{""name"":""Value"",""type"":""string""},{""name"":""Quality"",""default"":null,""type"":[""null"",""string""]}]}");
		private System.DateTime _TimeStamp;
		private string _DataChannelID;
		private string _Value;
		private string _Quality;
		public virtual Schema Schema
		{
			get
			{
				return EventDataSet._SCHEMA;
			}
		}
		public System.DateTime TimeStamp
		{
			get
			{
				return this._TimeStamp;
			}
			set
			{
				this._TimeStamp = value;
			}
		}
		public string DataChannelID
		{
			get
			{
				return this._DataChannelID;
			}
			set
			{
				this._DataChannelID = value;
			}
		}
		public string Value
		{
			get
			{
				return this._Value;
			}
			set
			{
				this._Value = value;
			}
		}
		public string Quality
		{
			get
			{
				return this._Quality;
			}
			set
			{
				this._Quality = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.TimeStamp;
			case 1: return this.DataChannelID;
			case 2: return this.Value;
			case 3: return this.Quality;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.TimeStamp = (System.DateTime)fieldValue; break;
			case 1: this.DataChannelID = (System.String)fieldValue; break;
			case 2: this.Value = (System.String)fieldValue; break;
			case 3: this.Quality = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
