// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Vista.SDK.Transport.Avro.TimeSeriesData
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	
	
	public partial class EventData : ISpecificRecord
	{
		public static Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""EventData"",""namespace"":""Vista.SDK.Transport.Avro.TimeSeriesData"",""fields"":[{""name"":""NumberOfDataSet"",""default"":null,""type"":[""null"",""string""]},{""name"":""DataSet"",""default"":null,""type"":[""null"",{""type"":""array"",""items"":{""type"":""record"",""name"":""EventDataSet"",""namespace"":""Vista.SDK.Transport.Avro.TimeSeriesData"",""fields"":[{""name"":""TimeStamp"",""type"":{""type"":""long"",""logicalType"":""timestamp-micros""}},{""name"":""DataChannelID"",""type"":""string""},{""name"":""Value"",""type"":""string""},{""name"":""Quality"",""default"":null,""type"":[""null"",""string""]}]}}]}]}");
		private string _NumberOfDataSet;
		private IList<global::Vista.SDK.Transport.Avro.TimeSeriesData.EventDataSet> _DataSet;
		public virtual Schema Schema
		{
			get
			{
				return EventData._SCHEMA;
			}
		}
		public string NumberOfDataSet
		{
			get
			{
				return this._NumberOfDataSet;
			}
			set
			{
				this._NumberOfDataSet = value;
			}
		}
		public IList<global::Vista.SDK.Transport.Avro.TimeSeriesData.EventDataSet> DataSet
		{
			get
			{
				return this._DataSet;
			}
			set
			{
				this._DataSet = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.NumberOfDataSet;
			case 1: return this.DataSet;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.NumberOfDataSet = (System.String)fieldValue; break;
			case 1: this.DataSet = (IList<global::Vista.SDK.Transport.Avro.TimeSeriesData.EventDataSet>)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
