// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Vista.SDK.Transport.Avro.TimeSeriesData
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	
	
	public partial class Package : ISpecificRecord
	{
		public static Schema _SCHEMA = global::Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"Package\",\"namespace\":\"Vista.SDK.Transport.Avro.TimeSeriesD" +
				"ata\",\"fields\":[{\"name\":\"Header\",\"default\":null,\"type\":[\"null\",{\"type\":\"record\",\"" +
				"name\":\"Header\",\"namespace\":\"Vista.SDK.Transport.Avro.TimeSeriesData\",\"fields\":[{\"n" +
				"ame\":\"ShipID\",\"type\":\"string\"},{\"name\":\"TimeSpan\",\"default\":null,\"type\":[\"null\"," +
				"{\"type\":\"record\",\"name\":\"TimeSpan\",\"namespace\":\"Vista.SDK.Transport.Avro.TimeSerie" +
				"sData\",\"fields\":[{\"name\":\"Start\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-" +
				"micros\"}},{\"name\":\"End\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-micros\"}}" +
				"]}]},{\"name\":\"DateCreated\",\"default\":null,\"type\":[\"null\",{\"type\":\"long\",\"logical" +
				"Type\":\"timestamp-micros\"}]},{\"name\":\"DateModified\",\"default\":null,\"type\":[\"null\"" +
				",{\"type\":\"long\",\"logicalType\":\"timestamp-micros\"}]},{\"name\":\"Author\",\"default\":n" +
				"ull,\"type\":[\"null\",\"string\"]},{\"name\":\"SystemConfiguration\",\"default\":null,\"type" +
				"\":[\"null\",{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"SystemConfiguration\"," +
				"\"namespace\":\"Vista.SDK.Transport.Avro.TimeSeriesData\",\"fields\":[{\"name\":\"ID\",\"type" +
				"\":\"string\"},{\"name\":\"TimeStamp\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-m" +
				"icros\"}}]}}]}]}]},{\"name\":\"TimeSeriesData\",\"type\":{\"type\":\"array\",\"items\":{\"type" +
				"\":\"record\",\"name\":\"TimeSeriesData\",\"namespace\":\"Vista.SDK.Transport.Avro.TimeSerie" +
				"sData\",\"fields\":[{\"name\":\"DataConfiguration\",\"default\":null,\"type\":[\"null\",{\"typ" +
				"e\":\"record\",\"name\":\"DataConfiguration\",\"namespace\":\"Vista.SDK.Transport.Avro.TimeS" +
				"eriesData\",\"fields\":[{\"name\":\"ID\",\"type\":\"string\"},{\"name\":\"TimeStamp\",\"type\":{\"" +
				"type\":\"long\",\"logicalType\":\"timestamp-micros\"}}]}]},{\"name\":\"TabularData\",\"defau" +
				"lt\":null,\"type\":[\"null\",{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Tabular" +
				"Data\",\"namespace\":\"Vista.SDK.Transport.Avro.TimeSeriesData\",\"fields\":[{\"name\":\"Num" +
				"berOfDataSet\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"NumberOfDataChan" +
				"nel\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"DataChannelID\",\"default\":" +
				"null,\"type\":[\"null\",{\"type\":\"array\",\"items\":\"string\"}]},{\"name\":\"DataSet\",\"defau" +
				"lt\":null,\"type\":[\"null\",{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Tabular" +
				"DataSet\",\"namespace\":\"Vista.SDK.Transport.Avro.TimeSeriesData\",\"fields\":[{\"name\":\"" +
				"TimeStamp\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-micros\"}},{\"name\":\"Val" +
				"ue\",\"type\":{\"type\":\"array\",\"items\":\"string\"}},{\"name\":\"Quality\",\"default\":null,\"" +
				"type\":[\"null\",{\"type\":\"array\",\"items\":\"string\"}]}]}}]}]}}]},{\"name\":\"EventData\"," +
				"\"default\":null,\"type\":[\"null\",{\"type\":\"record\",\"name\":\"EventData\",\"namespace\":\"V" +
				"IS.SDK.Transport.Avro.TimeSeriesData\",\"fields\":[{\"name\":\"NumberOfDataSet\",\"defau" +
				"lt\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"DataSet\",\"default\":null,\"type\":[\"nul" +
				"l\",{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"EventDataSet\",\"namespace\":\"V" +
				"IS.SDK.Transport.Avro.TimeSeriesData\",\"fields\":[{\"name\":\"TimeStamp\",\"type\":{\"typ" +
				"e\":\"long\",\"logicalType\":\"timestamp-micros\"}},{\"name\":\"DataChannelID\",\"type\":\"str" +
				"ing\"},{\"name\":\"Value\",\"type\":\"string\"},{\"name\":\"Quality\",\"default\":null,\"type\":[" +
				"\"null\",\"string\"]}]}}]}]}]}]}}}]}");
		private global::Vista.SDK.Transport.Avro.TimeSeriesData.Header _Header;
		private IList<global::Vista.SDK.Transport.Avro.TimeSeriesData.TimeSeriesData> _TimeSeriesData;
		public virtual Schema Schema
		{
			get
			{
				return Package._SCHEMA;
			}
		}
		public global::Vista.SDK.Transport.Avro.TimeSeriesData.Header Header
		{
			get
			{
				return this._Header;
			}
			set
			{
				this._Header = value;
			}
		}
		public IList<global::Vista.SDK.Transport.Avro.TimeSeriesData.TimeSeriesData> TimeSeriesData
		{
			get
			{
				return this._TimeSeriesData;
			}
			set
			{
				this._TimeSeriesData = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.Header;
			case 1: return this.TimeSeriesData;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.Header = (global::Vista.SDK.Transport.Avro.TimeSeriesData.Header)fieldValue; break;
			case 1: this.TimeSeriesData = (IList<global::Vista.SDK.Transport.Avro.TimeSeriesData.TimeSeriesData>)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
