// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Vista.SDK.Transport.Avro.TimeSeriesData
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	
	
	public partial class TabularData : ISpecificRecord
	{
		public static Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""TabularData"",""namespace"":""Vista.SDK.Transport.Avro.TimeSeriesData"",""fields"":[{""name"":""NumberOfDataSet"",""default"":null,""type"":[""null"",""string""]},{""name"":""NumberOfDataChannel"",""default"":null,""type"":[""null"",""string""]},{""name"":""DataChannelID"",""default"":null,""type"":[""null"",{""type"":""array"",""items"":""string""}]},{""name"":""DataSet"",""default"":null,""type"":[""null"",{""type"":""array"",""items"":{""type"":""record"",""name"":""TabularDataSet"",""namespace"":""Vista.SDK.Transport.Avro.TimeSeriesData"",""fields"":[{""name"":""TimeStamp"",""type"":{""type"":""long"",""logicalType"":""timestamp-micros""}},{""name"":""Value"",""type"":{""type"":""array"",""items"":""string""}},{""name"":""Quality"",""default"":null,""type"":[""null"",{""type"":""array"",""items"":""string""}]}]}}]}]}");
		private string _NumberOfDataSet;
		private string _NumberOfDataChannel;
		private IList<System.String> _DataChannelID;
		private IList<global::Vista.SDK.Transport.Avro.TimeSeriesData.TabularDataSet> _DataSet;
		public virtual Schema Schema
		{
			get
			{
				return TabularData._SCHEMA;
			}
		}
		public string NumberOfDataSet
		{
			get
			{
				return this._NumberOfDataSet;
			}
			set
			{
				this._NumberOfDataSet = value;
			}
		}
		public string NumberOfDataChannel
		{
			get
			{
				return this._NumberOfDataChannel;
			}
			set
			{
				this._NumberOfDataChannel = value;
			}
		}
		public IList<System.String> DataChannelID
		{
			get
			{
				return this._DataChannelID;
			}
			set
			{
				this._DataChannelID = value;
			}
		}
		public IList<global::Vista.SDK.Transport.Avro.TimeSeriesData.TabularDataSet> DataSet
		{
			get
			{
				return this._DataSet;
			}
			set
			{
				this._DataSet = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.NumberOfDataSet;
			case 1: return this.NumberOfDataChannel;
			case 2: return this.DataChannelID;
			case 3: return this.DataSet;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.NumberOfDataSet = (System.String)fieldValue; break;
			case 1: this.NumberOfDataChannel = (System.String)fieldValue; break;
			case 2: this.DataChannelID = (IList<System.String>)fieldValue; break;
			case 3: this.DataSet = (IList<global::Vista.SDK.Transport.Avro.TimeSeriesData.TabularDataSet>)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
