// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Vista.SDK.Transport.Avro.TimeSeriesData
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	
	
	public partial class TabularDataSet : ISpecificRecord
	{
		public static Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""TabularDataSet"",""namespace"":""Vista.SDK.Transport.Avro.TimeSeriesData"",""fields"":[{""name"":""TimeStamp"",""type"":{""type"":""long"",""logicalType"":""timestamp-micros""}},{""name"":""Value"",""type"":{""type"":""array"",""items"":""string""}},{""name"":""Quality"",""default"":null,""type"":[""null"",{""type"":""array"",""items"":""string""}]}]}");
		private System.DateTime _TimeStamp;
		private IList<System.String> _Value;
		private IList<System.String> _Quality;
		public virtual Schema Schema
		{
			get
			{
				return TabularDataSet._SCHEMA;
			}
		}
		public System.DateTime TimeStamp
		{
			get
			{
				return this._TimeStamp;
			}
			set
			{
				this._TimeStamp = value;
			}
		}
		public IList<System.String> Value
		{
			get
			{
				return this._Value;
			}
			set
			{
				this._Value = value;
			}
		}
		public IList<System.String> Quality
		{
			get
			{
				return this._Quality;
			}
			set
			{
				this._Quality = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.TimeStamp;
			case 1: return this.Value;
			case 2: return this.Quality;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.TimeStamp = (System.DateTime)fieldValue; break;
			case 1: this.Value = (IList<System.String>)fieldValue; break;
			case 2: this.Quality = (IList<System.String>)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
