// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Vista.SDK.Transport.Avro.TimeSeriesData
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	
	
	public partial class TimeSeriesData : ISpecificRecord
	{
		public static Schema _SCHEMA = global::Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"TimeSeriesData\",\"namespace\":\"Vista.SDK.Transport.Avro.Time" +
				"SeriesData\",\"fields\":[{\"name\":\"DataConfiguration\",\"default\":null,\"type\":[\"null\"," +
				"{\"type\":\"record\",\"name\":\"DataConfiguration\",\"namespace\":\"Vista.SDK.Transport.Avro." +
				"TimeSeriesData\",\"fields\":[{\"name\":\"ID\",\"type\":\"string\"},{\"name\":\"TimeStamp\",\"typ" +
				"e\":{\"type\":\"long\",\"logicalType\":\"timestamp-micros\"}}]}]},{\"name\":\"TabularData\",\"" +
				"default\":null,\"type\":[\"null\",{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Ta" +
				"bularData\",\"namespace\":\"Vista.SDK.Transport.Avro.TimeSeriesData\",\"fields\":[{\"name\"" +
				":\"NumberOfDataSet\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"NumberOfDat" +
				"aChannel\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"DataChannelID\",\"defa" +
				"ult\":null,\"type\":[\"null\",{\"type\":\"array\",\"items\":\"string\"}]},{\"name\":\"DataSet\",\"" +
				"default\":null,\"type\":[\"null\",{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Ta" +
				"bularDataSet\",\"namespace\":\"Vista.SDK.Transport.Avro.TimeSeriesData\",\"fields\":[{\"na" +
				"me\":\"TimeStamp\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-micros\"}},{\"name\"" +
				":\"Value\",\"type\":{\"type\":\"array\",\"items\":\"string\"}},{\"name\":\"Quality\",\"default\":n" +
				"ull,\"type\":[\"null\",{\"type\":\"array\",\"items\":\"string\"}]}]}}]}]}}]},{\"name\":\"EventD" +
				"ata\",\"default\":null,\"type\":[\"null\",{\"type\":\"record\",\"name\":\"EventData\",\"namespac" +
				"e\":\"Vista.SDK.Transport.Avro.TimeSeriesData\",\"fields\":[{\"name\":\"NumberOfDataSet\",\"" +
				"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"DataSet\",\"default\":null,\"type\":" +
				"[\"null\",{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"EventDataSet\",\"namespac" +
				"e\":\"Vista.SDK.Transport.Avro.TimeSeriesData\",\"fields\":[{\"name\":\"TimeStamp\",\"type\":" +
				"{\"type\":\"long\",\"logicalType\":\"timestamp-micros\"}},{\"name\":\"DataChannelID\",\"type\"" +
				":\"string\"},{\"name\":\"Value\",\"type\":\"string\"},{\"name\":\"Quality\",\"default\":null,\"ty" +
				"pe\":[\"null\",\"string\"]}]}}]}]}]}]}");
		private global::Vista.SDK.Transport.Avro.TimeSeriesData.DataConfiguration _DataConfiguration;
		private IList<global::Vista.SDK.Transport.Avro.TimeSeriesData.TabularData> _TabularData;
		private global::Vista.SDK.Transport.Avro.TimeSeriesData.EventData _EventData;
		public virtual Schema Schema
		{
			get
			{
				return TimeSeriesData._SCHEMA;
			}
		}
		public global::Vista.SDK.Transport.Avro.TimeSeriesData.DataConfiguration DataConfiguration
		{
			get
			{
				return this._DataConfiguration;
			}
			set
			{
				this._DataConfiguration = value;
			}
		}
		public IList<global::Vista.SDK.Transport.Avro.TimeSeriesData.TabularData> TabularData
		{
			get
			{
				return this._TabularData;
			}
			set
			{
				this._TabularData = value;
			}
		}
		public global::Vista.SDK.Transport.Avro.TimeSeriesData.EventData EventData
		{
			get
			{
				return this._EventData;
			}
			set
			{
				this._EventData = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.DataConfiguration;
			case 1: return this.TabularData;
			case 2: return this.EventData;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.DataConfiguration = (global::Vista.SDK.Transport.Avro.TimeSeriesData.DataConfiguration)fieldValue; break;
			case 1: this.TabularData = (IList<global::Vista.SDK.Transport.Avro.TimeSeriesData.TabularData>)fieldValue; break;
			case 2: this.EventData = (global::Vista.SDK.Transport.Avro.TimeSeriesData.EventData)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
