// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Vista.SDK.Transport.Avro.TimeSeriesData
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	
	
	public partial class TimeSpan : ISpecificRecord
	{
		public static Schema _SCHEMA = global::Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"TimeSpan\",\"namespace\":\"Vista.SDK.Transport.Avro.TimeSeries" +
				"Data\",\"fields\":[{\"name\":\"Start\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-m" +
				"icros\"}},{\"name\":\"End\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-micros\"}}]" +
				"}");
		private System.DateTime _Start;
		private System.DateTime _End;
		public virtual Schema Schema
		{
			get
			{
				return TimeSpan._SCHEMA;
			}
		}
		public System.DateTime Start
		{
			get
			{
				return this._Start;
			}
			set
			{
				this._Start = value;
			}
		}
		public System.DateTime End
		{
			get
			{
				return this._End;
			}
			set
			{
				this._End = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.Start;
			case 1: return this.End;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.Start = (System.DateTime)fieldValue; break;
			case 1: this.End = (System.DateTime)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
