// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Vista.SDK.Transport.Avro.DataChannel
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	
	
	public partial class ConfigurationReference : ISpecificRecord
	{
		public static Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""ConfigurationReference"",""namespace"":""Vista.SDK.Transport.Avro.DataChannel"",""fields"":[{""name"":""ID"",""type"":""string""},{""name"":""Version"",""default"":null,""type"":[""null"",""string""]},{""name"":""TimeStamp"",""type"":{""type"":""long"",""logicalType"":""timestamp-micros""}}]}");
		private string _ID;
		private string _Version;
		private System.DateTime _TimeStamp;
		public virtual Schema Schema
		{
			get
			{
				return ConfigurationReference._SCHEMA;
			}
		}
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				this._ID = value;
			}
		}
		public string Version
		{
			get
			{
				return this._Version;
			}
			set
			{
				this._Version = value;
			}
		}
		public System.DateTime TimeStamp
		{
			get
			{
				return this._TimeStamp;
			}
			set
			{
				this._TimeStamp = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.ID;
			case 1: return this.Version;
			case 2: return this.TimeStamp;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.ID = (System.String)fieldValue; break;
			case 1: this.Version = (System.String)fieldValue; break;
			case 2: this.TimeStamp = (System.DateTime)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
