// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Vista.SDK.Transport.Avro.DataChannel
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	
	
	public partial class DataChannel : ISpecificRecord
	{
		public static Schema _SCHEMA = global::Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"DataChannel\",\"namespace\":\"Vista.SDK.Transport.Avro.DataCha" +
				"nnel\",\"fields\":[{\"name\":\"DataChannelID\",\"type\":{\"type\":\"record\",\"name\":\"DataChan" +
				"nelID\",\"namespace\":\"Vista.SDK.Transport.Avro.DataChannel\",\"fields\":[{\"name\":\"Local" +
				"ID\",\"type\":\"string\"},{\"name\":\"ShortID\",\"default\":null,\"type\":[\"null\",\"string\"]}," +
				"{\"name\":\"NameObject\",\"default\":null,\"type\":[\"null\",{\"type\":\"record\",\"name\":\"Name" +
				"Object\",\"namespace\":\"Vista.SDK.Transport.Avro.DataChannel\",\"fields\":[{\"name\":\"Nami" +
				"ngRule\",\"type\":\"string\"}]}]}]}},{\"name\":\"Property\",\"type\":{\"type\":\"record\",\"name" +
				"\":\"Property\",\"namespace\":\"Vista.SDK.Transport.Avro.DataChannel\",\"fields\":[{\"name\":" +
				"\"DataChannelType\",\"type\":{\"type\":\"record\",\"name\":\"DataChannelType\",\"namespace\":\"" +
				"Vista.SDK.Transport.Avro.DataChannel\",\"fields\":[{\"name\":\"Type\",\"type\":\"string\"},{\"" +
				"name\":\"UpdateCycle\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"Calculatio" +
				"nPeriod\",\"default\":null,\"type\":[\"null\",\"string\"]}]}},{\"name\":\"Format\",\"type\":{\"t" +
				"ype\":\"record\",\"name\":\"Format\",\"namespace\":\"Vista.SDK.Transport.Avro.DataChannel\",\"" +
				"fields\":[{\"name\":\"Type\",\"type\":\"string\"},{\"name\":\"Restriction\",\"default\":null,\"t" +
				"ype\":[\"null\",{\"type\":\"record\",\"name\":\"Restriction\",\"namespace\":\"Vista.SDK.Transpor" +
				"t.Avro.DataChannel\",\"fields\":[{\"name\":\"Enumeration\",\"default\":null,\"type\":[\"null" +
				"\",{\"type\":\"array\",\"items\":\"string\"}]},{\"name\":\"FractionDigits\",\"default\":null,\"t" +
				"ype\":[\"null\",\"string\"]},{\"name\":\"Length\",\"default\":null,\"type\":[\"null\",\"string\"]" +
				"},{\"name\":\"MaxExclusive\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"MaxIn" +
				"clusive\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"MaxLength\",\"default\":" +
				"null,\"type\":[\"null\",\"string\"]},{\"name\":\"MinExclusive\",\"default\":null,\"type\":[\"nu" +
				"ll\",\"string\"]},{\"name\":\"MinInclusive\",\"default\":null,\"type\":[\"null\",\"string\"]},{" +
				"\"name\":\"MinLength\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"Pattern\",\"d" +
				"efault\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"TotalDigits\",\"default\":null,\"typ" +
				"e\":[\"null\",\"string\"]},{\"name\":\"WhiteSpace\",\"default\":null,\"type\":[\"null\",{\"type\"" +
				":\"enum\",\"name\":\"WhiteSpace\",\"namespace\":\"Vista.SDK.Transport.Avro.DataChannel\",\"sy" +
				"mbols\":[\"Preserve\",\"Replace\",\"Collapse\"]}]}]}]}]}},{\"name\":\"Range\",\"default\":nul" +
				"l,\"type\":[\"null\",{\"type\":\"record\",\"name\":\"Range\",\"namespace\":\"Vista.SDK.Transport." +
				"Avro.DataChannel\",\"fields\":[{\"name\":\"High\",\"type\":\"string\"},{\"name\":\"Low\",\"type\"" +
				":\"string\"}]}]},{\"name\":\"Unit\",\"default\":null,\"type\":[\"null\",{\"type\":\"record\",\"na" +
				"me\":\"Unit\",\"namespace\":\"Vista.SDK.Transport.Avro.DataChannel\",\"fields\":[{\"name\":\"U" +
				"nitSymbol\",\"type\":\"string\"},{\"name\":\"QuantityName\",\"default\":null,\"type\":[\"null\"" +
				",\"string\"]}]}]},{\"name\":\"QualityCoding\",\"default\":null,\"type\":[\"null\",\"string\"]}" +
				",{\"name\":\"AlertPriority\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"Name\"" +
				",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"Remarks\",\"default\":null,\"type" +
				"\":[\"null\",\"string\"]}]}}]}");
		private global::Vista.SDK.Transport.Avro.DataChannel.DataChannelID _DataChannelID;
		private global::Vista.SDK.Transport.Avro.DataChannel.Property _Property;
		public virtual Schema Schema
		{
			get
			{
				return DataChannel._SCHEMA;
			}
		}
		public global::Vista.SDK.Transport.Avro.DataChannel.DataChannelID DataChannelID
		{
			get
			{
				return this._DataChannelID;
			}
			set
			{
				this._DataChannelID = value;
			}
		}
		public global::Vista.SDK.Transport.Avro.DataChannel.Property Property
		{
			get
			{
				return this._Property;
			}
			set
			{
				this._Property = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.DataChannelID;
			case 1: return this.Property;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.DataChannelID = (global::Vista.SDK.Transport.Avro.DataChannel.DataChannelID)fieldValue; break;
			case 1: this.Property = (global::Vista.SDK.Transport.Avro.DataChannel.Property)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
