// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Vista.SDK.Transport.Avro.DataChannel
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	
	
	public partial class DataChannelType : ISpecificRecord
	{
		public static Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""DataChannelType"",""namespace"":""Vista.SDK.Transport.Avro.DataChannel"",""fields"":[{""name"":""Type"",""type"":""string""},{""name"":""UpdateCycle"",""default"":null,""type"":[""null"",""string""]},{""name"":""CalculationPeriod"",""default"":null,""type"":[""null"",""string""]}]}");
		private string _Type;
		private string _UpdateCycle;
		private string _CalculationPeriod;
		public virtual Schema Schema
		{
			get
			{
				return DataChannelType._SCHEMA;
			}
		}
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				this._Type = value;
			}
		}
		public string UpdateCycle
		{
			get
			{
				return this._UpdateCycle;
			}
			set
			{
				this._UpdateCycle = value;
			}
		}
		public string CalculationPeriod
		{
			get
			{
				return this._CalculationPeriod;
			}
			set
			{
				this._CalculationPeriod = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.Type;
			case 1: return this.UpdateCycle;
			case 2: return this.CalculationPeriod;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.Type = (System.String)fieldValue; break;
			case 1: this.UpdateCycle = (System.String)fieldValue; break;
			case 2: this.CalculationPeriod = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
