// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Vista.SDK.Transport.Avro.DataChannel
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	
	
	public partial class DataChannelList : ISpecificRecord
	{
		public static Schema _SCHEMA = global::Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"DataChannelList\",\"namespace\":\"Vista.SDK.Transport.Avro.Dat" +
				"aChannel\",\"fields\":[{\"name\":\"DataChannel\",\"type\":{\"type\":\"array\",\"items\":{\"type\"" +
				":\"record\",\"name\":\"DataChannel\",\"namespace\":\"Vista.SDK.Transport.Avro.DataChannel\"," +
				"\"fields\":[{\"name\":\"DataChannelID\",\"type\":{\"type\":\"record\",\"name\":\"DataChannelID\"" +
				",\"namespace\":\"Vista.SDK.Transport.Avro.DataChannel\",\"fields\":[{\"name\":\"LocalID\",\"t" +
				"ype\":\"string\"},{\"name\":\"ShortID\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name" +
				"\":\"NameObject\",\"default\":null,\"type\":[\"null\",{\"type\":\"record\",\"name\":\"NameObject" +
				"\",\"namespace\":\"Vista.SDK.Transport.Avro.DataChannel\",\"fields\":[{\"name\":\"NamingRule" +
				"\",\"type\":\"string\"}]}]}]}},{\"name\":\"Property\",\"type\":{\"type\":\"record\",\"name\":\"Pro" +
				"perty\",\"namespace\":\"Vista.SDK.Transport.Avro.DataChannel\",\"fields\":[{\"name\":\"DataC" +
				"hannelType\",\"type\":{\"type\":\"record\",\"name\":\"DataChannelType\",\"namespace\":\"VIS.SD" +
				"K.Transport.Avro.DataChannel\",\"fields\":[{\"name\":\"Type\",\"type\":\"string\"},{\"name\":" +
				"\"UpdateCycle\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"CalculationPerio" +
				"d\",\"default\":null,\"type\":[\"null\",\"string\"]}]}},{\"name\":\"Format\",\"type\":{\"type\":\"" +
				"record\",\"name\":\"Format\",\"namespace\":\"Vista.SDK.Transport.Avro.DataChannel\",\"fields" +
				"\":[{\"name\":\"Type\",\"type\":\"string\"},{\"name\":\"Restriction\",\"default\":null,\"type\":[" +
				"\"null\",{\"type\":\"record\",\"name\":\"Restriction\",\"namespace\":\"Vista.SDK.Transport.Avro" +
				".DataChannel\",\"fields\":[{\"name\":\"Enumeration\",\"default\":null,\"type\":[\"null\",{\"ty" +
				"pe\":\"array\",\"items\":\"string\"}]},{\"name\":\"FractionDigits\",\"default\":null,\"type\":[" +
				"\"null\",\"string\"]},{\"name\":\"Length\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"na" +
				"me\":\"MaxExclusive\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"MaxInclusiv" +
				"e\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"MaxLength\",\"default\":null,\"" +
				"type\":[\"null\",\"string\"]},{\"name\":\"MinExclusive\",\"default\":null,\"type\":[\"null\",\"s" +
				"tring\"]},{\"name\":\"MinInclusive\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\"" +
				":\"MinLength\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"Pattern\",\"default" +
				"\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"TotalDigits\",\"default\":null,\"type\":[\"n" +
				"ull\",\"string\"]},{\"name\":\"WhiteSpace\",\"default\":null,\"type\":[\"null\",{\"type\":\"enum" +
				"\",\"name\":\"WhiteSpace\",\"namespace\":\"Vista.SDK.Transport.Avro.DataChannel\",\"symbols\"" +
				":[\"Preserve\",\"Replace\",\"Collapse\"]}]}]}]}]}},{\"name\":\"Range\",\"default\":null,\"typ" +
				"e\":[\"null\",{\"type\":\"record\",\"name\":\"Range\",\"namespace\":\"Vista.SDK.Transport.Avro.D" +
				"ataChannel\",\"fields\":[{\"name\":\"High\",\"type\":\"string\"},{\"name\":\"Low\",\"type\":\"stri" +
				"ng\"}]}]},{\"name\":\"Unit\",\"default\":null,\"type\":[\"null\",{\"type\":\"record\",\"name\":\"U" +
				"nit\",\"namespace\":\"Vista.SDK.Transport.Avro.DataChannel\",\"fields\":[{\"name\":\"UnitSym" +
				"bol\",\"type\":\"string\"},{\"name\":\"QuantityName\",\"default\":null,\"type\":[\"null\",\"stri" +
				"ng\"]}]}]},{\"name\":\"QualityCoding\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"nam" +
				"e\":\"AlertPriority\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"Name\",\"defa" +
				"ult\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"Remarks\",\"default\":null,\"type\":[\"nu" +
				"ll\",\"string\"]}]}}]}}}]}");
		private IList<global::Vista.SDK.Transport.Avro.DataChannel.DataChannel> _DataChannel;
		public virtual Schema Schema
		{
			get
			{
				return DataChannelList._SCHEMA;
			}
		}
		public IList<global::Vista.SDK.Transport.Avro.DataChannel.DataChannel> DataChannel
		{
			get
			{
				return this._DataChannel;
			}
			set
			{
				this._DataChannel = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.DataChannel;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.DataChannel = (IList<global::Vista.SDK.Transport.Avro.DataChannel.DataChannel>)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
