// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Vista.SDK.Transport.Avro.DataChannel
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	
	
	/// <summary>
	/// A DataChannelList package for ISO19848
	/// </summary>
	public partial class DataChannelListPackage : ISpecificRecord
	{
		public static Schema _SCHEMA = global::Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"DataChannelListPackage\",\"doc\":\"A DataChannelList package" +
				" for ISO19848\",\"namespace\":\"Vista.SDK.Transport.Avro.DataChannel\",\"fields\":[{\"name" +
				"\":\"Package\",\"type\":{\"type\":\"record\",\"name\":\"Package\",\"namespace\":\"Vista.SDK.Transp" +
				"ort.Avro.DataChannel\",\"fields\":[{\"name\":\"Header\",\"type\":{\"type\":\"record\",\"name\":" +
				"\"Header\",\"namespace\":\"Vista.SDK.Transport.Avro.DataChannel\",\"fields\":[{\"name\":\"Shi" +
				"pID\",\"type\":\"string\"},{\"name\":\"DataChannelListID\",\"type\":{\"type\":\"record\",\"name\"" +
				":\"ConfigurationReference\",\"namespace\":\"Vista.SDK.Transport.Avro.DataChannel\",\"fiel" +
				"ds\":[{\"name\":\"ID\",\"type\":\"string\"},{\"name\":\"Version\",\"default\":null,\"type\":[\"nul" +
				"l\",\"string\"]},{\"name\":\"TimeStamp\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp" +
				"-micros\"}}]}},{\"name\":\"VersionInformation\",\"default\":null,\"type\":[\"null\",{\"type\"" +
				":\"record\",\"name\":\"VersionInformation\",\"namespace\":\"Vista.SDK.Transport.Avro.DataCh" +
				"annel\",\"fields\":[{\"name\":\"NamingRule\",\"type\":\"string\"},{\"name\":\"NamingSchemeVers" +
				"ion\",\"type\":\"string\"},{\"name\":\"ReferenceURL\",\"default\":null,\"type\":[\"null\",\"stri" +
				"ng\"]}]}]},{\"name\":\"Author\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"Dat" +
				"eCreated\",\"default\":null,\"type\":[\"null\",{\"type\":\"long\",\"logicalType\":\"timestamp-" +
				"micros\"}]}]}},{\"name\":\"DataChannelList\",\"type\":{\"type\":\"record\",\"name\":\"DataChan" +
				"nelList\",\"namespace\":\"Vista.SDK.Transport.Avro.DataChannel\",\"fields\":[{\"name\":\"Dat" +
				"aChannel\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"DataChannel\",\"" +
				"namespace\":\"Vista.SDK.Transport.Avro.DataChannel\",\"fields\":[{\"name\":\"DataChannelID" +
				"\",\"type\":{\"type\":\"record\",\"name\":\"DataChannelID\",\"namespace\":\"Vista.SDK.Transport." +
				"Avro.DataChannel\",\"fields\":[{\"name\":\"LocalID\",\"type\":\"string\"},{\"name\":\"ShortID\"" +
				",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"NameObject\",\"default\":null,\"t" +
				"ype\":[\"null\",{\"type\":\"record\",\"name\":\"NameObject\",\"namespace\":\"Vista.SDK.Transport" +
				".Avro.DataChannel\",\"fields\":[{\"name\":\"NamingRule\",\"type\":\"string\"}]}]}]}},{\"name" +
				"\":\"Property\",\"type\":{\"type\":\"record\",\"name\":\"Property\",\"namespace\":\"Vista.SDK.Tran" +
				"sport.Avro.DataChannel\",\"fields\":[{\"name\":\"DataChannelType\",\"type\":{\"type\":\"reco" +
				"rd\",\"name\":\"DataChannelType\",\"namespace\":\"Vista.SDK.Transport.Avro.DataChannel\",\"f" +
				"ields\":[{\"name\":\"Type\",\"type\":\"string\"},{\"name\":\"UpdateCycle\",\"default\":null,\"ty" +
				"pe\":[\"null\",\"string\"]},{\"name\":\"CalculationPeriod\",\"default\":null,\"type\":[\"null\"" +
				",\"string\"]}]}},{\"name\":\"Format\",\"type\":{\"type\":\"record\",\"name\":\"Format\",\"namespa" +
				"ce\":\"Vista.SDK.Transport.Avro.DataChannel\",\"fields\":[{\"name\":\"Type\",\"type\":\"string" +
				"\"},{\"name\":\"Restriction\",\"default\":null,\"type\":[\"null\",{\"type\":\"record\",\"name\":\"" +
				"Restriction\",\"namespace\":\"Vista.SDK.Transport.Avro.DataChannel\",\"fields\":[{\"name\":" +
				"\"Enumeration\",\"default\":null,\"type\":[\"null\",{\"type\":\"array\",\"items\":\"string\"}]}," +
				"{\"name\":\"FractionDigits\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"Lengt" +
				"h\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"MaxExclusive\",\"default\":nul" +
				"l,\"type\":[\"null\",\"string\"]},{\"name\":\"MaxInclusive\",\"default\":null,\"type\":[\"null\"" +
				",\"string\"]},{\"name\":\"MaxLength\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\"" +
				":\"MinExclusive\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"MinInclusive\"," +
				"\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"MinLength\",\"default\":null,\"typ" +
				"e\":[\"null\",\"string\"]},{\"name\":\"Pattern\",\"default\":null,\"type\":[\"null\",\"string\"]}" +
				",{\"name\":\"TotalDigits\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"WhiteSp" +
				"ace\",\"default\":null,\"type\":[\"null\",{\"type\":\"enum\",\"name\":\"WhiteSpace\",\"namespace" +
				"\":\"Vista.SDK.Transport.Avro.DataChannel\",\"symbols\":[\"Preserve\",\"Replace\",\"Collapse" +
				"\"]}]}]}]}]}},{\"name\":\"Range\",\"default\":null,\"type\":[\"null\",{\"type\":\"record\",\"nam" +
				"e\":\"Range\",\"namespace\":\"Vista.SDK.Transport.Avro.DataChannel\",\"fields\":[{\"name\":\"H" +
				"igh\",\"type\":\"string\"},{\"name\":\"Low\",\"type\":\"string\"}]}]},{\"name\":\"Unit\",\"default" +
				"\":null,\"type\":[\"null\",{\"type\":\"record\",\"name\":\"Unit\",\"namespace\":\"Vista.SDK.Transp" +
				"ort.Avro.DataChannel\",\"fields\":[{\"name\":\"UnitSymbol\",\"type\":\"string\"},{\"name\":\"Q" +
				"uantityName\",\"default\":null,\"type\":[\"null\",\"string\"]}]}]},{\"name\":\"QualityCoding" +
				"\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"AlertPriority\",\"default\":nul" +
				"l,\"type\":[\"null\",\"string\"]},{\"name\":\"Name\",\"default\":null,\"type\":[\"null\",\"string" +
				"\"]},{\"name\":\"Remarks\",\"default\":null,\"type\":[\"null\",\"string\"]}]}}]}}}]}}]}}]}");
		private global::Vista.SDK.Transport.Avro.DataChannel.Package _Package;
		public virtual Schema Schema
		{
			get
			{
				return DataChannelListPackage._SCHEMA;
			}
		}
		public global::Vista.SDK.Transport.Avro.DataChannel.Package Package
		{
			get
			{
				return this._Package;
			}
			set
			{
				this._Package = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.Package;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.Package = (global::Vista.SDK.Transport.Avro.DataChannel.Package)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
