// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Vista.SDK.Transport.Avro.DataChannel
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	
	
	public partial class Format : ISpecificRecord
	{
		public static Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""Format"",""namespace"":""Vista.SDK.Transport.Avro.DataChannel"",""fields"":[{""name"":""Type"",""type"":""string""},{""name"":""Restriction"",""default"":null,""type"":[""null"",{""type"":""record"",""name"":""Restriction"",""namespace"":""Vista.SDK.Transport.Avro.DataChannel"",""fields"":[{""name"":""Enumeration"",""default"":null,""type"":[""null"",{""type"":""array"",""items"":""string""}]},{""name"":""FractionDigits"",""default"":null,""type"":[""null"",""string""]},{""name"":""Length"",""default"":null,""type"":[""null"",""string""]},{""name"":""MaxExclusive"",""default"":null,""type"":[""null"",""string""]},{""name"":""MaxInclusive"",""default"":null,""type"":[""null"",""string""]},{""name"":""MaxLength"",""default"":null,""type"":[""null"",""string""]},{""name"":""MinExclusive"",""default"":null,""type"":[""null"",""string""]},{""name"":""MinInclusive"",""default"":null,""type"":[""null"",""string""]},{""name"":""MinLength"",""default"":null,""type"":[""null"",""string""]},{""name"":""Pattern"",""default"":null,""type"":[""null"",""string""]},{""name"":""TotalDigits"",""default"":null,""type"":[""null"",""string""]},{""name"":""WhiteSpace"",""default"":null,""type"":[""null"",{""type"":""enum"",""name"":""WhiteSpace"",""namespace"":""Vista.SDK.Transport.Avro.DataChannel"",""symbols"":[""Preserve"",""Replace"",""Collapse""]}]}]}]}]}");
		private string _Type;
		private global::Vista.SDK.Transport.Avro.DataChannel.Restriction _Restriction;
		public virtual Schema Schema
		{
			get
			{
				return Format._SCHEMA;
			}
		}
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				this._Type = value;
			}
		}
		public global::Vista.SDK.Transport.Avro.DataChannel.Restriction Restriction
		{
			get
			{
				return this._Restriction;
			}
			set
			{
				this._Restriction = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.Type;
			case 1: return this.Restriction;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.Type = (System.String)fieldValue; break;
			case 1: this.Restriction = (global::Vista.SDK.Transport.Avro.DataChannel.Restriction)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
