// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Vista.SDK.Transport.Avro.DataChannel
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	
	
	public partial class Header : ISpecificRecord
	{
		public static Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""Header"",""namespace"":""Vista.SDK.Transport.Avro.DataChannel"",""fields"":[{""name"":""ShipID"",""type"":""string""},{""name"":""DataChannelListID"",""type"":{""type"":""record"",""name"":""ConfigurationReference"",""namespace"":""Vista.SDK.Transport.Avro.DataChannel"",""fields"":[{""name"":""ID"",""type"":""string""},{""name"":""Version"",""default"":null,""type"":[""null"",""string""]},{""name"":""TimeStamp"",""type"":{""type"":""long"",""logicalType"":""timestamp-micros""}}]}},{""name"":""VersionInformation"",""default"":null,""type"":[""null"",{""type"":""record"",""name"":""VersionInformation"",""namespace"":""Vista.SDK.Transport.Avro.DataChannel"",""fields"":[{""name"":""NamingRule"",""type"":""string""},{""name"":""NamingSchemeVersion"",""type"":""string""},{""name"":""ReferenceURL"",""default"":null,""type"":[""null"",""string""]}]}]},{""name"":""Author"",""default"":null,""type"":[""null"",""string""]},{""name"":""DateCreated"",""default"":null,""type"":[""null"",{""type"":""long"",""logicalType"":""timestamp-micros""}]}]}");
		private string _ShipID;
		private global::Vista.SDK.Transport.Avro.DataChannel.ConfigurationReference _DataChannelListID;
		private global::Vista.SDK.Transport.Avro.DataChannel.VersionInformation _VersionInformation;
		private string _Author;
		private System.Nullable<System.DateTime> _DateCreated;
		public virtual Schema Schema
		{
			get
			{
				return Header._SCHEMA;
			}
		}
		public string ShipID
		{
			get
			{
				return this._ShipID;
			}
			set
			{
				this._ShipID = value;
			}
		}
		public global::Vista.SDK.Transport.Avro.DataChannel.ConfigurationReference DataChannelListID
		{
			get
			{
				return this._DataChannelListID;
			}
			set
			{
				this._DataChannelListID = value;
			}
		}
		public global::Vista.SDK.Transport.Avro.DataChannel.VersionInformation VersionInformation
		{
			get
			{
				return this._VersionInformation;
			}
			set
			{
				this._VersionInformation = value;
			}
		}
		public string Author
		{
			get
			{
				return this._Author;
			}
			set
			{
				this._Author = value;
			}
		}
		public System.Nullable<System.DateTime> DateCreated
		{
			get
			{
				return this._DateCreated;
			}
			set
			{
				this._DateCreated = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.ShipID;
			case 1: return this.DataChannelListID;
			case 2: return this.VersionInformation;
			case 3: return this.Author;
			case 4: return this.DateCreated;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.ShipID = (System.String)fieldValue; break;
			case 1: this.DataChannelListID = (global::Vista.SDK.Transport.Avro.DataChannel.ConfigurationReference)fieldValue; break;
			case 2: this.VersionInformation = (global::Vista.SDK.Transport.Avro.DataChannel.VersionInformation)fieldValue; break;
			case 3: this.Author = (System.String)fieldValue; break;
			case 4: this.DateCreated = (System.Nullable<System.DateTime>)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
