// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Vista.SDK.Transport.Avro.DataChannel
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	
	
	public partial class NameObject : ISpecificRecord
	{
		public static Schema _SCHEMA = global::Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"NameObject\",\"namespace\":\"Vista.SDK.Transport.Avro.DataChan" +
				"nel\",\"fields\":[{\"name\":\"NamingRule\",\"type\":\"string\"}]}");
		private string _NamingRule;
		public virtual Schema Schema
		{
			get
			{
				return NameObject._SCHEMA;
			}
		}
		public string NamingRule
		{
			get
			{
				return this._NamingRule;
			}
			set
			{
				this._NamingRule = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.NamingRule;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.NamingRule = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
