// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Vista.SDK.Transport.Avro.DataChannel
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	
	
	public partial class Package : ISpecificRecord
	{
		public static Schema _SCHEMA = global::Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"Package\",\"namespace\":\"Vista.SDK.Transport.Avro.DataChannel" +
				"\",\"fields\":[{\"name\":\"Header\",\"type\":{\"type\":\"record\",\"name\":\"Header\",\"namespace\"" +
				":\"Vista.SDK.Transport.Avro.DataChannel\",\"fields\":[{\"name\":\"ShipID\",\"type\":\"string\"" +
				"},{\"name\":\"DataChannelListID\",\"type\":{\"type\":\"record\",\"name\":\"ConfigurationRefer" +
				"ence\",\"namespace\":\"Vista.SDK.Transport.Avro.DataChannel\",\"fields\":[{\"name\":\"ID\",\"t" +
				"ype\":\"string\"},{\"name\":\"Version\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name" +
				"\":\"TimeStamp\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-micros\"}}]}},{\"name" +
				"\":\"VersionInformation\",\"default\":null,\"type\":[\"null\",{\"type\":\"record\",\"name\":\"Ve" +
				"rsionInformation\",\"namespace\":\"Vista.SDK.Transport.Avro.DataChannel\",\"fields\":[{\"n" +
				"ame\":\"NamingRule\",\"type\":\"string\"},{\"name\":\"NamingSchemeVersion\",\"type\":\"string\"" +
				"},{\"name\":\"ReferenceURL\",\"default\":null,\"type\":[\"null\",\"string\"]}]}]},{\"name\":\"A" +
				"uthor\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"DateCreated\",\"default\":" +
				"null,\"type\":[\"null\",{\"type\":\"long\",\"logicalType\":\"timestamp-micros\"}]}]}},{\"name" +
				"\":\"DataChannelList\",\"type\":{\"type\":\"record\",\"name\":\"DataChannelList\",\"namespace\"" +
				":\"Vista.SDK.Transport.Avro.DataChannel\",\"fields\":[{\"name\":\"DataChannel\",\"type\":{\"t" +
				"ype\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"DataChannel\",\"namespace\":\"Vista.SDK." +
				"Transport.Avro.DataChannel\",\"fields\":[{\"name\":\"DataChannelID\",\"type\":{\"type\":\"re" +
				"cord\",\"name\":\"DataChannelID\",\"namespace\":\"Vista.SDK.Transport.Avro.DataChannel\",\"f" +
				"ields\":[{\"name\":\"LocalID\",\"type\":\"string\"},{\"name\":\"ShortID\",\"default\":null,\"typ" +
				"e\":[\"null\",\"string\"]},{\"name\":\"NameObject\",\"default\":null,\"type\":[\"null\",{\"type\"" +
				":\"record\",\"name\":\"NameObject\",\"namespace\":\"Vista.SDK.Transport.Avro.DataChannel\",\"" +
				"fields\":[{\"name\":\"NamingRule\",\"type\":\"string\"}]}]}]}},{\"name\":\"Property\",\"type\":" +
				"{\"type\":\"record\",\"name\":\"Property\",\"namespace\":\"Vista.SDK.Transport.Avro.DataChann" +
				"el\",\"fields\":[{\"name\":\"DataChannelType\",\"type\":{\"type\":\"record\",\"name\":\"DataChan" +
				"nelType\",\"namespace\":\"Vista.SDK.Transport.Avro.DataChannel\",\"fields\":[{\"name\":\"Typ" +
				"e\",\"type\":\"string\"},{\"name\":\"UpdateCycle\",\"default\":null,\"type\":[\"null\",\"string\"" +
				"]},{\"name\":\"CalculationPeriod\",\"default\":null,\"type\":[\"null\",\"string\"]}]}},{\"nam" +
				"e\":\"Format\",\"type\":{\"type\":\"record\",\"name\":\"Format\",\"namespace\":\"Vista.SDK.Transpo" +
				"rt.Avro.DataChannel\",\"fields\":[{\"name\":\"Type\",\"type\":\"string\"},{\"name\":\"Restrict" +
				"ion\",\"default\":null,\"type\":[\"null\",{\"type\":\"record\",\"name\":\"Restriction\",\"namesp" +
				"ace\":\"Vista.SDK.Transport.Avro.DataChannel\",\"fields\":[{\"name\":\"Enumeration\",\"defau" +
				"lt\":null,\"type\":[\"null\",{\"type\":\"array\",\"items\":\"string\"}]},{\"name\":\"FractionDig" +
				"its\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"Length\",\"default\":null,\"t" +
				"ype\":[\"null\",\"string\"]},{\"name\":\"MaxExclusive\",\"default\":null,\"type\":[\"null\",\"st" +
				"ring\"]},{\"name\":\"MaxInclusive\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":" +
				"\"MaxLength\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"MinExclusive\",\"def" +
				"ault\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"MinInclusive\",\"default\":null,\"type" +
				"\":[\"null\",\"string\"]},{\"name\":\"MinLength\",\"default\":null,\"type\":[\"null\",\"string\"]" +
				"},{\"name\":\"Pattern\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"TotalDigit" +
				"s\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"WhiteSpace\",\"default\":null," +
				"\"type\":[\"null\",{\"type\":\"enum\",\"name\":\"WhiteSpace\",\"namespace\":\"Vista.SDK.Transport" +
				".Avro.DataChannel\",\"symbols\":[\"Preserve\",\"Replace\",\"Collapse\"]}]}]}]}]}},{\"name\"" +
				":\"Range\",\"default\":null,\"type\":[\"null\",{\"type\":\"record\",\"name\":\"Range\",\"namespac" +
				"e\":\"Vista.SDK.Transport.Avro.DataChannel\",\"fields\":[{\"name\":\"High\",\"type\":\"string\"" +
				"},{\"name\":\"Low\",\"type\":\"string\"}]}]},{\"name\":\"Unit\",\"default\":null,\"type\":[\"null" +
				"\",{\"type\":\"record\",\"name\":\"Unit\",\"namespace\":\"Vista.SDK.Transport.Avro.DataChannel" +
				"\",\"fields\":[{\"name\":\"UnitSymbol\",\"type\":\"string\"},{\"name\":\"QuantityName\",\"defaul" +
				"t\":null,\"type\":[\"null\",\"string\"]}]}]},{\"name\":\"QualityCoding\",\"default\":null,\"ty" +
				"pe\":[\"null\",\"string\"]},{\"name\":\"AlertPriority\",\"default\":null,\"type\":[\"null\",\"st" +
				"ring\"]},{\"name\":\"Name\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"Remarks" +
				"\",\"default\":null,\"type\":[\"null\",\"string\"]}]}}]}}}]}}]}");
		private global::Vista.SDK.Transport.Avro.DataChannel.Header _Header;
		private global::Vista.SDK.Transport.Avro.DataChannel.DataChannelList _DataChannelList;
		public virtual Schema Schema
		{
			get
			{
				return Package._SCHEMA;
			}
		}
		public global::Vista.SDK.Transport.Avro.DataChannel.Header Header
		{
			get
			{
				return this._Header;
			}
			set
			{
				this._Header = value;
			}
		}
		public global::Vista.SDK.Transport.Avro.DataChannel.DataChannelList DataChannelList
		{
			get
			{
				return this._DataChannelList;
			}
			set
			{
				this._DataChannelList = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.Header;
			case 1: return this.DataChannelList;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.Header = (global::Vista.SDK.Transport.Avro.DataChannel.Header)fieldValue; break;
			case 1: this.DataChannelList = (global::Vista.SDK.Transport.Avro.DataChannel.DataChannelList)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
