// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Vista.SDK.Transport.Avro.DataChannel
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	
	
	public partial class Unit : ISpecificRecord
	{
		public static Schema _SCHEMA = global::Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"Unit\",\"namespace\":\"Vista.SDK.Transport.Avro.DataChannel\",\"" +
				"fields\":[{\"name\":\"UnitSymbol\",\"type\":\"string\"},{\"name\":\"QuantityName\",\"default\":" +
				"null,\"type\":[\"null\",\"string\"]}]}");
		private string _UnitSymbol;
		private string _QuantityName;
		public virtual Schema Schema
		{
			get
			{
				return Unit._SCHEMA;
			}
		}
		public string UnitSymbol
		{
			get
			{
				return this._UnitSymbol;
			}
			set
			{
				this._UnitSymbol = value;
			}
		}
		public string QuantityName
		{
			get
			{
				return this._QuantityName;
			}
			set
			{
				this._QuantityName = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.UnitSymbol;
			case 1: return this.QuantityName;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.UnitSymbol = (System.String)fieldValue; break;
			case 1: this.QuantityName = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
