// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Vista.SDK.Transport.Avro.DataChannel
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	
	
	public partial class VersionInformation : ISpecificRecord
	{
		public static Schema _SCHEMA = global::Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"VersionInformation\",\"namespace\":\"Vista.SDK.Transport.Avro." +
				"DataChannel\",\"fields\":[{\"name\":\"NamingRule\",\"type\":\"string\"},{\"name\":\"NamingSche" +
				"meVersion\",\"type\":\"string\"},{\"name\":\"ReferenceURL\",\"default\":null,\"type\":[\"null\"" +
				",\"string\"]}]}");
		private string _NamingRule;
		private string _NamingSchemeVersion;
		private string _ReferenceURL;
		public virtual Schema Schema
		{
			get
			{
				return VersionInformation._SCHEMA;
			}
		}
		public string NamingRule
		{
			get
			{
				return this._NamingRule;
			}
			set
			{
				this._NamingRule = value;
			}
		}
		public string NamingSchemeVersion
		{
			get
			{
				return this._NamingSchemeVersion;
			}
			set
			{
				this._NamingSchemeVersion = value;
			}
		}
		public string ReferenceURL
		{
			get
			{
				return this._ReferenceURL;
			}
			set
			{
				this._ReferenceURL = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.NamingRule;
			case 1: return this.NamingSchemeVersion;
			case 2: return this.ReferenceURL;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.NamingRule = (System.String)fieldValue; break;
			case 1: this.NamingSchemeVersion = (System.String)fieldValue; break;
			case 2: this.ReferenceURL = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
