using Test
using VistaSdk

include("core/test_vis.jl")
include("core/test_vis_versions.jl")
include("core/test_codebook_name.jl")
include("core/test_codebooks.jl")
include("core/test_parsing_errors.jl")
include("core/test_locations.jl")
include("core/test_imo_number.jl")
include("core/test_gmod_node.jl")
include("core/test_gmod_node_metadata.jl")
include("core/test_gmod.jl")
include("core/test_gmod_path.jl")
include("core/test_local_id.jl")
include("core/test_universal_id.jl")
include("core/test_vis_versioning.jl")
include("query/test_metadata_tags_query.jl")
include("query/test_gmod_path_query.jl")
include("query/test_local_id_query.jl")
include("transport/test_iso19848_version.jl")
include("transport/test_iso19848.jl")
include("transport/test_ship_id.jl")
include("transport/test_serializable_document.jl")
include("transport/datachannel/test_data_channel.jl")
include("transport/datachannel/test_datachannel_dto.jl")
include("transport/datachannel/test_data_channel_json.jl")
include("transport/timeseries/test_time_series_data_channel_id.jl")
include("transport/timeseries/test_time_series_data.jl")
include("transport/timeseries/test_time_series_data_json.jl")
include("transport/timeseries/test_time_series_data_dto.jl")
include("types/test_datetime.jl")
include("types/test_decimal.jl")
