/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * An experimental generalized TimeSeriesData package based on ISO19848
 */
export namespace TimeSeriesDto {

export interface TimeSeriesDataPackage {
  Package: Package;
}
export interface Package {
  Header?: Header;
  TimeSeriesData: TimeSeriesData[];
}
export interface Header {
  AssetId: string;
  TimeSpan?: TimeSpan;
  DateCreated?: Date;
  DateModified?: Date;
  Author?: string;
  SystemConfiguration?: ConfigurationReference[];
  [k: string]: unknown;
}
export interface TimeSpan {
  Start: Date;
  End: Date;
}
export interface ConfigurationReference {
  ID: string;
  TimeStamp: Date;
}
export interface TimeSeriesData {
  DataConfiguration?: ConfigurationReference;
  TabularData?: TabularData[];
  EventData?: EventData;
  [k: string]: unknown;
}
export interface TabularData {
  NumberOfDataSet?: string;
  NumberOfDataPoints?: string;
  DataId?: string[];
  DataSet?: TabularDataSet[];
}
export interface TabularDataSet {
  TimeStamp: Date;
  Value: string[];
  Quality?: string[];
}
export interface EventData {
  NumberOfDataSet?: string;
  DataSet?: EventDataSet[];
}
export interface EventDataSet {
  TimeStamp: Date;
  DataId: string;
  Value: string;
  Quality?: string;
}

}