/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * An experimental generalized DataList package based on ISO19848
 */
export namespace DataListDto {

export interface DataListPackage {
  Package: Package;
}
export interface Package {
  Header: Header;
  DataList: DataList;
}
export interface Header {
  AssetId: string;
  DataListID: ConfigurationReference;
  VersionInformation?: VersionInformation;
  Author?: string;
  DateCreated?: Date;
  [k: string]: unknown;
}
export interface ConfigurationReference {
  ID: string;
  Version?: string;
  TimeStamp: Date;
}
export interface VersionInformation {
  NamingRule: string;
  NamingSchemeVersion: string;
  ReferenceURL?: string;
}
export interface DataList {
  Data: Data[];
}
export interface Data {
  DataID: DataID;
  Property: Property;
}
export interface DataID {
  LocalID: string;
  ShortID?: string;
  NameObject?: NameObject;
}
export interface NameObject {
  NamingRule: string;
  [k: string]: unknown;
}
export interface Property {
  DataType: DataType;
  Format: Format;
  Range?: Range;
  Unit?: Unit;
  QualityCoding?: string;
  AlertPriority?: string;
  Name?: string;
  Remarks?: string;
  [k: string]: unknown;
}
export interface DataType {
  Type: string;
  UpdateCycle?: string;
  CalculationPeriod?: string;
}
export interface Format {
  Type: string;
  Restriction?: Restriction;
}
export interface Restriction {
  Enumeration?: string[];
  FractionDigits?: string;
  Length?: string;
  MaxExclusive?: string;
  MaxInclusive?: string;
  MaxLength?: string;
  MinExclusive?: string;
  MinInclusive?: string;
  MinLength?: string;
  Pattern?: string;
  TotalDigits?: string;
  WhiteSpace?: "Preserve" | "Replace" | "Collapse";
}
export interface Range {
  High: string;
  Low: string;
}
export interface Unit {
  UnitSymbol: string;
  QuantityName?: string;
  [k: string]: unknown;
}

}