/**
 * @file ISO19848VersionsGenerator.cpp
 * @brief ISO 19848 version header generator tool
 * @details Generates ISO19848Versions.h (public API) and ISO19848VersionsExtensions.h (internal utilities) from
 * embedded ISO 19848 resource files
 */

#include <ResourcesRegistry.h>

#include <algorithm>
#include <cstdio>
#include <filesystem>
#include <format>
#include <fstream>
#include <string>
#include <vector>

namespace fs = std::filesystem;

using namespace dnv::vista::sdk;

static bool writeFile(const fs::path& outputPath, const std::string& content)
{
    std::error_code ec;
    fs::create_directories(outputPath.parent_path(), ec);
    if (ec)
    {
        std::fprintf(
            stderr,
            "Failed to create directory: %s (%s)\n",
            outputPath.parent_path().string().c_str(),
            ec.message().c_str());
        return false;
    }

    std::ofstream outputFile(outputPath, std::ios::binary);
    if (!outputFile)
    {
        std::fprintf(stderr, "Failed to open output file: %s\n", outputPath.string().c_str());
        return false;
    }

    outputFile.write(content.data(), static_cast<std::streamsize>(content.size()));

    if (!outputFile)
    {
        std::fprintf(stderr, "Failed to write to output file: %s\n", outputPath.string().c_str());
        return false;
    }

    return true;
}

static std::string enumName(const std::string& version)
{
    std::string name = version;
    std::replace(name.begin(), name.end(), '-', '_');
    return name;
}

static bool generateISO19848VersionHeader(
    const std::vector<std::string>& versions, const fs::path& outputPath, std::string_view sdkVersion)
{
    std::string out;

    out += std::format(
        "/**\n"
        " * @file ISO19848Versions.h\n"
        " * @brief Type-safe enumeration of ISO 19848 versions\n"
        " * @details AUTO-GENERATED FILE - DO NOT EDIT - Generated by: ISO19848VersionsGenerator (dnv-vista-sdk v{})\n"
        " */\n"
        "\n"
        "#pragma once\n"
        "\n"
        "#include <cstdint>\n"
        "#include <optional>\n"
        "#include <string_view>\n"
        "\n"
        "namespace dnv::vista::sdk::transport\n"
        "{{\n"
        "    /**\n"
        "     * @brief ISO 19848 standard versions\n"
        "     */\n"
        "    enum class ISO19848Version : std::uint8_t\n"
        "    {{\n",
        sdkVersion);

    for (size_t i = 0; i < versions.size(); ++i)
    {
        out += std::format(
            "        {}{} ///< ISO 19848:{}\n",
            enumName(versions[i]),
            i + 1 < versions.size() ? "," : "",
            versions[i].substr(1));
    }

    out +=
        "    };\n"
        "\n"
        "    /**\n"
        "     * @brief ISO 19848 version utilities\n"
        "     */\n"
        "    namespace ISO19848Versions\n"
        "    {\n"
        "        [[nodiscard]] constexpr std::string_view toString(ISO19848Version version) noexcept\n"
        "        {\n"
        "            switch (version)\n"
        "            {\n";

    for (const auto& v : versions)
    {
        out += std::format(
            "                case ISO19848Version::{}:\n"
            "                    return \"{}\";\n",
            enumName(v),
            v);
    }

    out +=
        "                default:\n"
        "                    return \"\";\n"
        "            }\n"
        "        }\n"
        "\n"
        "        [[nodiscard]] constexpr std::optional<ISO19848Version> fromString(std::string_view version) noexcept\n"
        "        {\n";

    for (const auto& v : versions)
    {
        out += std::format(
            "            if (version == \"{}\")\n"
            "            {{\n"
            "                return ISO19848Version::{};\n"
            "            }}\n",
            v,
            enumName(v));
    }

    out +=
        "            return std::nullopt;\n"
        "        }\n"
        "    } // namespace ISO19848Versions\n"
        "} // namespace dnv::vista::sdk::transport\n";

    return writeFile(outputPath, out);
}

static bool generateISO19848VersionExtensionsHeader(
    const std::vector<std::string>& versions, const fs::path& outputPath, std::string_view sdkVersion)
{
    std::string out;

    out += std::format(
        "/**\n"
        " * @file ISO19848VersionsExtensions.h\n"
        " * @brief Internal ISO 19848 version utilities for SDK implementation\n"
        " * @details AUTO-GENERATED FILE - DO NOT EDIT - Generated by: ISO19848VersionsGenerator (dnv-vista-sdk v{})\n"
        " */\n"
        "\n"
        "#pragma once\n"
        "\n"
        "#include \"dnv/vista/sdk/transport/ISO19848Versions.h\"\n"
        "\n"
        "#include <array>\n"
        "#include <string_view>\n"
        "\n"
        "namespace dnv::vista::sdk::transport\n"
        "{{\n"
        "/**\n"
        " * @brief Internal ISO 19848 version utilities\n"
        " * @note For internal SDK use only\n"
        " */\n"
        "    namespace ISO19848Versions\n"
        "    {{\n"
        "        /**\n"
        "         * @brief Array of all ISO 19848 versions enum values\n"
        "         * @return Array containing all ISO 19848 version enum values\n"
        "         */\n"
        "        constexpr std::array<ISO19848Version, {}> all()\n"
        "        {{\n"
        "            return {{\n",
        sdkVersion,
        versions.size());

    for (size_t i = 0; i < versions.size(); ++i)
    {
        out += std::format(
            "                ISO19848Version::{}{}\n", enumName(versions[i]), i + 1 < versions.size() ? "," : "");
    }

    out +=
        "            };\n"
        "        }\n"
        "\n"
        "        /**\n"
        "         * @brief Get the latest available ISO 19848 version\n"
        "         * @return The latest ISO 19848 version\n"
        "         */\n"
        "        constexpr ISO19848Version latest() noexcept\n"
        "        {\n"
        "            constexpr auto versions = all();\n"
        "            return versions.back();\n"
        "        }\n"
        "\n"
        "    } // namespace ISO19848Versions\n"
        "} // namespace dnv::vista::sdk::transport\n";

    return writeFile(outputPath, out);
}

int main(int argc, char* argv[])
{
    if (argc < 4)
    {
        std::fprintf(
            stderr, "Usage: ISO19848VersionsGenerator <public_header_path> <extensions_header_path> <sdk_version>\n");
        return 1;
    }

    fs::path iso19848VersionHeaderPath = argv[1];
    fs::path iso19848VersionExtensionsPath = argv[2];
    std::string_view sdkVersion = argv[3];

    std::printf("Loading ISO 19848 versions from embedded resources...\n");

    const auto& resources = resources::all();
    std::vector<std::string> versions;

    for (const auto& res : resources)
    {
        constexpr std::string_view prefix = "iso19848-";
        constexpr std::string_view suffix = ".json.gz";

        if (!res.name.starts_with(prefix) || !res.name.ends_with(suffix))
        {
            continue;
        }

        auto versionStart = prefix.size();
        auto dashAfterVersion = res.name.find('-', versionStart);
        if (dashAfterVersion == std::string_view::npos)
        {
            continue;
        }

        std::string version{ res.name.substr(versionStart, dashAfterVersion - versionStart) };

        if (std::find(versions.begin(), versions.end(), version) == versions.end())
        {
            versions.emplace_back(std::move(version));
        }
    }

    if (versions.empty())
    {
        std::fprintf(stderr, "No ISO 19848 versions found!\n");
        return 1;
    }

    std::sort(versions.begin(), versions.end());

    std::printf("Found %zu ISO 19848 versions:\n", versions.size());
    for (const auto& version : versions)
    {
        std::printf("  - %s\n", version.c_str());
    }

    std::printf("Generating public header: %s\n", iso19848VersionHeaderPath.string().c_str());

    if (!generateISO19848VersionHeader(versions, iso19848VersionHeaderPath, sdkVersion))
    {
        return 1;
    }

    std::printf("Generating extensions header: %s\n", iso19848VersionExtensionsPath.string().c_str());

    if (!generateISO19848VersionExtensionsHeader(versions, iso19848VersionExtensionsPath, sdkVersion))
    {
        return 1;
    }

    return 0;
}
