/**
 * @file VisVersionsGenerator.cpp
 * @brief VIS version header generator tool
 * @details Generates VisVersions.h (public API) and VisVersionsExtensions.h (internal utilities) from embedded VIS
 * resource files
 */

#include <ResourcesRegistry.h>

#include <algorithm>
#include <cstdio>
#include <filesystem>
#include <format>
#include <fstream>
#include <string>
#include <vector>

namespace fs = std::filesystem;

using namespace dnv::vista::sdk;

static bool writeFile(const fs::path& outputPath, const std::string& content)
{
    std::error_code ec;
    fs::create_directories(outputPath.parent_path(), ec);
    if (ec)
    {
        std::fprintf(
            stderr,
            "Failed to create directory: %s (%s)\n",
            outputPath.parent_path().string().c_str(),
            ec.message().c_str());
        return false;
    }

    std::ofstream outputFile(outputPath, std::ios::binary);
    if (!outputFile)
    {
        std::fprintf(stderr, "Failed to open output file: %s\n", outputPath.string().c_str());
        return false;
    }

    outputFile.write(content.data(), static_cast<std::streamsize>(content.size()));

    if (!outputFile)
    {
        std::fprintf(stderr, "Failed to write to output file: %s\n", outputPath.string().c_str());
        return false;
    }

    return true;
}

static std::string enumName(const std::string& version)
{
    std::string name = version;
    std::replace(name.begin(), name.end(), '-', '_');
    return name;
}

static bool generateVisVersionHeader(
    const std::vector<std::string>& versions, const fs::path& outputPath, std::string_view sdkVersion)
{
    std::string out;

    out += std::format(
        "/**\n"
        " * @file VisVersions.h\n"
        " * @brief Type-safe enumeration of VIS versions\n"
        " * @details AUTO-GENERATED FILE - DO NOT EDIT - Generated by: VisVersionsGenerator (dnv-vista-sdk v{})\n"
        " */\n"
        "\n"
        "#pragma once\n"
        "\n"
        "#include <cstdint>\n"
        "#include <optional>\n"
        "#include <string_view>\n"
        "\n"
        "namespace dnv::vista::sdk\n"
        "{{\n"
        "    /**\n"
        "     * @brief Enumeration of VIS versions\n"
        "     */\n"
        "    enum class VisVersion : std::uint8_t\n"
        "    {{\n",
        sdkVersion);

    for (size_t i = 0; i < versions.size(); ++i)
    {
        out += std::format("        v{}{}\n", enumName(versions[i]), i + 1 < versions.size() ? "," : "");
    }

    out +=
        "    };\n"
        "\n"
        "    /**\n"
        "     * @brief VIS version utilities\n"
        "     */\n"
        "    namespace VisVersions\n"
        "    {\n"
        "        [[nodiscard]] constexpr std::string_view toString(VisVersion version) noexcept\n"
        "        {\n"
        "            switch (version)\n"
        "            {\n";

    for (const auto& v : versions)
    {
        out += std::format(
            "                case VisVersion::v{}:\n"
            "                    return \"{}\";\n",
            enumName(v),
            v);
    }

    out +=
        "                default:\n"
        "                    return \"\";\n"
        "            }\n"
        "        }\n"
        "\n"
        "        [[nodiscard]] constexpr bool fromString(std::string_view version, VisVersion& result) noexcept\n"
        "        {\n";

    for (const auto& v : versions)
    {
        out += std::format(
            "            if (version == \"{}\")\n"
            "            {{\n"
            "                result = VisVersion::v{};\n"
            "                return true;\n"
            "            }}\n",
            v,
            enumName(v));
    }

    out +=
        "            return false;\n"
        "        }\n"
        "\n"
        "        [[nodiscard]] constexpr std::optional<VisVersion> fromString(std::string_view version) noexcept\n"
        "        {\n";

    for (const auto& v : versions)
    {
        out += std::format(
            "            if (version == \"{}\")\n"
            "            {{\n"
            "                return VisVersion::v{};\n"
            "            }}\n",
            v,
            enumName(v));
    }

    out +=
        "            return std::nullopt;\n"
        "        }\n"
        "    } // namespace VisVersions\n"
        "} // namespace dnv::vista::sdk\n";

    return writeFile(outputPath, out);
}

static bool generateVisVersionExtensionsHeader(
    const std::vector<std::string>& versions, const fs::path& outputPath, std::string_view sdkVersion)
{
    std::string out;

    out += std::format(
        "/**\n"
        " * @file VisVersionsExtensions.h\n"
        " * @brief Internal VIS version utilities for SDK implementation\n"
        " * @details AUTO-GENERATED FILE - DO NOT EDIT - Generated by: VisVersionsGenerator (dnv-vista-sdk v{})\n"
        " */\n"
        "\n"
        "#pragma once\n"
        "\n"
        "#include \"dnv/vista/sdk/core/VisVersions.h\"\n"
        "\n"
        "#include <array>\n"
        "\n"
        "namespace dnv::vista::sdk\n"
        "{{\n"
        "    /**\n"
        "     * @brief Internal VIS version utilities\n"
        "     * @note For internal SDK use only\n"
        "     */\n"
        "    namespace VisVersions\n"
        "    {{\n"
        "        constexpr std::array<VisVersion, {}> all()\n"
        "        {{\n"
        "            return {{\n",
        sdkVersion,
        versions.size());

    for (size_t i = 0; i < versions.size(); ++i)
    {
        out += std::format(
            "                VisVersion::v{}{}\n", enumName(versions[i]), i + 1 < versions.size() ? "," : "");
    }

    out +=
        "            };\n"
        "        }\n"
        "\n"
        "        constexpr VisVersion latest() noexcept\n"
        "        {\n"
        "            constexpr auto versions = all();\n"
        "            return versions.back();\n"
        "        }\n"
        "\n"
        "        constexpr bool isValid(VisVersion version) noexcept\n"
        "        {\n"
        "            switch (version)\n"
        "            {\n";

    for (const auto& v : versions)
    {
        out += std::format("                case VisVersion::v{}:\n", enumName(v));
    }

    out +=
        "                    return true;\n"
        "                default:\n"
        "                    return false;\n"
        "            }\n"
        "        }\n"
        "\n"
        "    } // namespace VisVersions\n"
        "} // namespace dnv::vista::sdk\n";

    return writeFile(outputPath, out);
}

int main(int argc, char* argv[])
{
    if (argc < 4)
    {
        std::fprintf(
            stderr, "Usage: VisVersionsGenerator <public_header_path> <extensions_header_path> <sdk_version>\n");
        return 1;
    }

    fs::path visVersionHeaderPath = argv[1];
    fs::path visVersionExtensionsPath = argv[2];
    std::string_view sdkVersion = argv[3];

    std::printf("Loading VIS versions from embedded resources...\n");

    const auto& resources = resources::all();
    std::vector<std::string> versions;

    for (const auto& res : resources)
    {
        if (res.name.ends_with(".gz") && res.name.find("gmod") != std::string_view::npos &&
            res.name.find("versioning") == std::string_view::npos)
        {
            constexpr std::string_view prefix = "gmod-vis-";
            constexpr std::string_view suffix = ".json.gz";

            auto prefixPos = res.name.find(prefix);
            if (prefixPos != std::string_view::npos)
            {
                auto versionStart = prefixPos + prefix.size();
                auto suffixPos = res.name.find(suffix, versionStart);
                if (suffixPos != std::string_view::npos)
                {
                    versions.emplace_back(res.name.substr(versionStart, suffixPos - versionStart));
                }
            }
        }
    }

    if (versions.empty())
    {
        std::fprintf(stderr, "No VIS versions found!\n");
        return 1;
    }

    std::sort(versions.begin(), versions.end(), [](const std::string& a, const std::string& b) {
        auto parse = [](const std::string& v) -> std::pair<int, int> {
            auto dash = v.find('-');
            if (dash == std::string::npos)
            {
                return { 0, 0 };
            }
            int major = std::stoi(v.substr(0, dash));
            int minor = std::stoi(v.substr(dash + 1));
            return { major, minor };
        };
        return parse(a) < parse(b);
    });

    std::printf("Found %zu VIS versions:\n", versions.size());
    for (const auto& version : versions)
    {
        std::printf("  - %s\n", version.c_str());
    }

    std::printf("Generating public header: %s\n", visVersionHeaderPath.string().c_str());

    if (!generateVisVersionHeader(versions, visVersionHeaderPath, sdkVersion))
    {
        return 1;
    }

    std::printf("Generating extensions header: %s\n", visVersionExtensionsPath.string().c_str());

    if (!generateVisVersionExtensionsHeader(versions, visVersionExtensionsPath, sdkVersion))
    {
        return 1;
    }

    return 0;
}
